### ISSUE TITLE
Synchronize with recent CoreMark

### ISSUE THREAD

**Issue by jserv** [kuopinghsu/srv32#8]
It has been a long time since last source adaptation of [eembc/coremark](https://github.com/eembc/coremark). Directory [sw/coremark](https://github.com/kuopinghsu/srv32/tree/master/sw/coremark) contains an old copy, and it would be nice to use git submodule to synchronize with recent CoreMark instead of C source file duplications.

**Comment by kuopinghsu** [comment]
CoreMark hasn't been updated for a long time, the most recent change is to fix some typos. I think I will keep a copy to make some modifications.

**Comment by kuopinghsu** [comment]
No plans to sync with coremark's master branch
